# -*- coding: utf-8 -*-
"""membership_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fsL17xCybXioAhk40By8nCi4s_VySsK
"""

!pip install -U scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

# Generate universe variables
x = np.arange(0, 11, 1)

# Generate fuzzy membership functions
# Triangular membership function
triangular_mf = fuzz.trimf(x, [3, 6, 9])

# Trapezoidal membership function
trapezoidal_mf = fuzz.trapmf(x, [2, 4, 7, 9])

# Gaussian membership function
gaussian_mf = fuzz.gaussmf(x, np.mean(x), np.std(x))

# Plot the membership functions
plt.figure()

plt.plot(x, triangular_mf, 'b', label='Triangular MF')
plt.plot(x, trapezoidal_mf, 'g', label='Trapezoidal MF')
plt.plot(x, gaussian_mf, 'r', label='Gaussian MF')

plt.title('Membership Functions')
plt.xlabel('X')
plt.ylabel('Membership')
plt.legend()
plt.grid()

plt.show()