# -*- coding: utf-8 -*-
"""member_funipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujM7_K-UNudwE0pMec7yqUa8iT0Suk4w
"""

!pip install -U scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

# Generate universe variables
x = np.arange(0, 11, 1)

# Generate triangular membership function
triangular_mf = fuzz.trimf(x, [3, 6, 9])

# Plot the triangular membership function
plt.figure()
plt.plot(x, triangular_mf, 'b', label='Triangular MF')
plt.title('Triangular Membership Function')
plt.xlabel('X')
plt.ylabel('Membership')
plt.legend()
plt.grid()
plt.show()

# Generate trapezoidal membership function
trapezoidal_mf = fuzz.trapmf(x, [2, 4, 7, 9])

# Plot the trapezoidal membership function
plt.figure()
plt.plot(x, trapezoidal_mf, 'g', label='Trapezoidal MF')
plt.title('Trapezoidal Membership Function')
plt.xlabel('X')
plt.ylabel('Membership')
plt.legend()
plt.grid()
plt.show()

# Generate Gaussian membership function
gaussian_mf = fuzz.gaussmf(x, np.mean(x), np.std(x))

# Plot the Gaussian membership function
plt.figure()
plt.plot(x, gaussian_mf, 'r', label='Gaussian MF')
plt.title('Gaussian Membership Function')
plt.xlabel('X')
plt.ylabel('Membership')
plt.legend()
plt.grid()
plt.show()