# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNvkq1I3RggT3zC8p7XTEdOj6Xdyfkxn
"""

!pip install -U scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Define input variable
temperature = ctrl.Antecedent(np.arange(0, 101, 1), 'temperature')

# Define membership functions
temperature['cold'] = fuzz.trimf(temperature.universe, [0, 0, 50])
temperature['medium'] = fuzz.trimf(temperature.universe, [20, 50, 80])
temperature['hot'] = fuzz.trimf(temperature.universe, [50, 100, 100])

# Define output variable
fan_speed = ctrl.Consequent(np.arange(0, 101, 1), 'fan_speed')

# Define membership functions
fan_speed['low'] = fuzz.trimf(fan_speed.universe, [0, 0, 50])
fan_speed['medium'] = fuzz.trimf(fan_speed.universe, [20, 50, 80])
fan_speed['high'] = fuzz.trimf(fan_speed.universe, [50, 100, 100])

rule1 = ctrl.Rule(temperature['cold'], fan_speed['low'])
rule2 = ctrl.Rule(temperature['medium'], fan_speed['medium'])
rule3 = ctrl.Rule(temperature['hot'], fan_speed['high'])

fan_speed_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

fan_speed_simulator = ctrl.ControlSystemSimulation(fan_speed_ctrl)
fan_speed_simulator.input['temperature'] = 40  # Input temperature
fan_speed_simulator.compute()

print("Fan Speed:", fan_speed_simulator.output['fan_speed'])